version: "3.3"
services:
  client:
    container_name: client-container
    restart: always
    build: ./front-end
    ports:
      - "80:8080"
    depends_on:
      - api
  api:
    container_name: api-container
    restart: always
    build: ./back-end
    ports:
      - "5000:5000"
ports:
  - 
